"""updated user moidel

Revision ID: d0dc20ea42e2
Revises: e1081e20b389
Create Date: 2024-05-03 12:43:52.563025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0dc20ea42e2'
down_revision = 'e1081e20b389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('barber_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_client_id_clients'), 'clients', ['client_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_users_barber_id_barbers'), 'barbers', ['barber_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_barber_id_barbers'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_users_client_id_clients'), type_='foreignkey')
        batch_op.drop_column('client_id')
        batch_op.drop_column('barber_id')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
